@startuml
:PKI Admin: as Admin
:PKI Root Admin: as RootAdmin
RootAdmin-|>Admin
:PKI User: as User
(PKCS ceremony of key initialization) as (Key Init)

(Strong authentication & encryption) as (StrongAuth)
Alice -> Sender
Bob -> Receiver
Sender --|> User
Receiver -|> User
User -> (StrongAuth)

Admin --> (Key Init)
RootAdmin --> (Key Init)

note right of Admin
At least 2 for
keyring initialization
end note

note right of (Key Init)
Initiates and validates
the root key generation
end note

note "Basic keystore scenarios" as N2
(StrongAuth) .. N2
N2 .. (Key Init)
@enduml